name: terraform-workflow
run-name: "Ran by ${{github.actor}} on ${{github.event_name}} to ${{github.ref_name}}, testing terraform building "
on:
    push:
        paths:
            - "terraform/**"
jobs:
    tf-infra-check:
        runs-on: ubuntu-24.04

        defaults:
            run:
                working-directory: ./terraform                     # to avoid repeating cd ./terraform
        
        env:
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            TF_VAR_ip: ${{secrets.MY_IP}}
            AWS_REGION: ${{vars.AWS_REGION}}
        steps:
            - name: "Clone /terraform"
              uses: actions/checkout@v6.0.2

            - name: "Setup terraform"
              uses: hashicorp/setup-terraform@v3.1.2

            - run: terraform init
            - run: terraform plan
